name: Deploy

on:
  push:
      branches:
        - upload

  workflow_dispatch:


jobs:
  get-banners:
    name: "Get banners data"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: upload

      - uses: actions/upload-artifact@v4
        with:
          name: banners-data
          path: banners.json

  build:
    needs: get-banners
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Remove temp banners data"
        run: rm frontend/src/banners.json

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: banners-data
          path: frontend/src

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: frontend/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist