name: Deploy

on:
  workflow_dispatch:
    inputs:
      bannersData:
        description: "List of banners"
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: create file
        run: echo "${{ github.event.inputs.bannersData }}" > file.txt

      - name: output file
        run: cat file.txt