name: Deploy

on:
  workflow_dispatch:
    inputs:
      bannersData:
        description: "List of banners"
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write banners data
        run: echo "${{ github.event.inputs.bannersData }}" > frontend/src/banners.json

      - name: test
        run: cat frontend/src/banners.json


# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4

#       - name: Install dependencies
#         uses: bahmutov/npm-install@v1

#       - name: Build project
#         run: npm run build

#       - name: Upload production-ready build files
#         uses: actions/upload-artifact@v4
#         with:
#           name: production-files
#           path: ./dist